// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/Mizi/works/hulu/demo29/node_modules/dumi/theme-default/builtins/SourceCode/index.js';
